### PR TITLE
More SDK API alignement + new commands in acls to show-identities + views query-sparql output is not shown as table

### PR DESCRIPTION
**Pull request by samuel-kerrien**

### CODE REVIEW

**Review by MFSY — COMMENTED** [review]
I think in projects.py the base argument needs to be removed in create at:

response = nxs.projects.create(org_label=_org_label, project_label=label, description=description,
                                       api_mappings=mappings, vocab=vocab, base = base)

The sdk don't have it anymore.

**Comment by samuel-kerrien** [comment]
you may have a stale version of the nexus-python-sdk, you might want to run `pip uninstall nexus-python-sdk` and then reinstall it again ... I had the same problem this afternoon.

**Review by MFSY — COMMENTED** [review]
True.

**Review by MFSY — APPROVED** [review]
True.

**Pull request merged**
